### ISSUE TITLE
Can we also please add a column for membership status? i.e. member/non-member.  This is so churches can import bulk membership lists directly

### ISSUE THREAD

**Issue by lsamon** [adventistmedia/adventisthub-support#113]

**Comment by danlewis** [comment]
added

**Comment by cristiansc** [comment]
Just downloaded CSV - Membership column pre-filled with AU - this should be in Country Code :)

**Comment by cristiansc** [comment]
Also, tried it, I typed in non-member in membership-status column and wouldn't accept it - would only accept "non_member"

Can we pre-fill the first entry with non_member? so users know how it needs to be typed? 'member' is obvious

**Comment by cristiansc** [comment]
also the last column is called 'description' and it creates an auto 'todo' activity with the category 'decision' . Can we make it an 'enquiry' rather than a decision? or even better, add an activity type called 'note' which simply becomes a way to tag/log non-standard or new activities that don't fit into other categories?

**Comment by danlewis** [comment]
non_member added to template by default in the correct column.
The last column does say "decision".
Adding of notes would be a seperate feature when we get to adding the notes feature
