### ISSUE TITLE
Auto-postcode sorting

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#12]
Can we create a bulk import method that auto-allocates contacts by postcodes? I imagine it will take a bit of work to map postcodes, but in the long run I think it will be very valuable - e.g. we had 3,000+ hero of hacksaw ridge book requests - manually allocating each one is very time consuming.

**Comment by amnwebmaster** [comment]
Auto allocation is definitely where I'd like see the AH ending up. There are a couple questions that need answering to figure out how that will actually work

1. It would be much better if we went straight for coordinate (lat & lng) based allocation. In a Hub team under settings a team manager can set their team address which would be used to pair up contacts based on their address.
The problem with postcodes is that they don't work in all countries and they need to be kept up-to-date. In Australia as noted here (https://auspost.com.au/about-us/corporate-information/our-company/policies/assignment-of-postcodes) Australia Post may introduce, retire or change postcodes at any time.
Recommendation: Coordinates

2. How in a team should the contact be allocated? Should it allocate to:
a) the team but no members (let the manager allocation)
b) team manager 
c) best team member based on (gender, likes, age), default to a) or b)

Recommendation: C, defaulting to A. 
As part of implementing C, a simple profile about the users interests should be created. e.g. please select your interests: sport, history, family, health, ...

3) What happens when no team can be matched to a contact?

Thoughts: stick with the current system where self allocation occurs

4) Special Hub Teams e.g. Arise Bible Workers, don't necessarily operate where their building is. How would get contacts allocated? 

Thoughts: Maybe they should be a separate upload. I'm guessing most bible workers would actually belong to a church and not the Arise bible school

5) Contacts in the country are a little harder to match. For example a team might be the closest match but if their 200km away that might not be realistic.

Thoughts: maybe when searching for a team to allocate it only finds churches within 50km max.

**Comment by cristiansc** [comment]
1. I agree with coordinates - will take some time to map, but better in the long run - great suggestion

2. My preference would be A - provided the manager receives a notification that the contact has been added to their team and that the accountability process is mapped to the manager. I would hesitate with C due to the changing nature of local church landscapes. e.g. an incident may have occurred rendering a user inappropriate to follow-up a contact. If the manager has not restricted access to the user (which is likely to be overlooked at least in the initial stages of familiarity with AH) then the contact may end up in the wrong hands.

3. My preference would be to stick with the geo coordinates. If a contact has been assigned to the wrong team through geo cords, then that manager is probably the best person to know where it should go as they live and/or work in that region.

4. Again, allocate to team/manager - who can then re-assign to correct Bible worker.

5. Again, my preference is for geo cords without creating limiting distances. If a contact is too far away yet still closer to Church A more than any other, than Church A still needs to find a solution. If it can't, then Church A needs to work with the local conference to find a solution (e.g. more staffing, BW's, etc.

Happy to chat about this further on the phone if needed as well :)

**Comment by danlewis** [comment]
Auto assigning of contacts to team has now been implemented. Here's how it works:

Requirements:
1) Team must have a latitude and longitude which is automatically set via the address
2) Team must have a manager
3) Team must be active
4) Contact must have a latitude and longitude which is automatically set via the contacts home address
5) Contact must not have a Hub team or User assigned already

Process:
1. For a contact, find the nearest team in the contacts country that is no more than 1000km away and has a team manger
3. Assign the contact to the team
4. Create an alert for the team manager saying: A new contact #{name} has been assigned to #{hub_team.name}. Please assign them to a user in the team

How:
There are two places auto assigning can be done.
a. In the HQ, go to Contacts > Unassigned and click Auto-assign to team.
b. After bulk uploading contacts in the HQ, on completion a button to Auto-assign to team is shown.

Follow Up:
Any teams who do not assign their contacts after two weeks can be found on the HQ dashboard where you can see the number of abandoned contacts (contacts who have not been updated in two weeks and have no user assigned).

**Comment by danlewis** [comment]
This feature is now live. Closing ticket.
