### ISSUE TITLE
Org log-in not working for WA director

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#132]
Tried to create org account for Nic Dumbrava - nicudumbrava@adventist.org.au

would not let him log-in, repeatedly. Tried logging in/out of team - tried different browser - kept on coming up with 'unauthorised' login on the purple log-in screen.

**Comment by brettdonald** [comment]
Sent an email to Nicu with my contact details, and asked him to contact me.

**Comment by danlewis** [comment]
The error message is correct.
Nic is a pending user in the Western Australia organisation and hence can not login until he has accepted the invite.

**Comment by brettdonald** [comment]
Nicu's issue has been resolved. Quick explanation of the cause follows.

When someone is invited to join a new team, AdHub checks their email address to see whether they are an existing user. This is important because the desired result is to have a single user with multiple memberships. However, in Nicu's case the email check failed to find him as an existing user, because his email address was typed in **mixed case**, and the comparison was not properly ignoring case in the comparison. This resulted in him being sent a "new user" invitation instead of a "join a new team" invitation, and then being unable to accept the invitation.

So, the bug has been fixed, Nicu was re-invited to the WA organisation. The correct "join a new team" invitation was sent, and he was able to accept that and log in successfully.

**Comment by cristiansc** [comment]
Great - thanks for following up.
