### ISSUE TITLE
Add Event work-flow

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#20]
Can we have the drop down 'add event' menu appear as soon as you click on the 'events' tab?
At the moment you have to select 'add event' but not sure of the function of this button as you click once, then click 'add event' below again to add an event.  Perhaps do away with the 'greyed out' "Add new event" button, just leave the jade button as is, and have the 'Recurring events' tab show right up?

**Comment by amnwebmaster** [comment]
Having the "add event" panel hidden on page load is done because it 
a) makes the page initially much more simpler to familiar a user with the page
b) the panel when, their are a number of recurring events can get really big.. e.g. for me i have 3 recurring events which makes the page big enough that I can't even see the events table below

I agree there there can be some improvements to layout though.. so I'll think a little more about it..

**Comment by cristiansc** [comment]
Makes sense - thanks for clarifying

**Comment by danlewis** [comment]
Events has been updated to have a simpler UI - hopefully this resolves the question
