### ISSUE TITLE
Autofill Drop Down Menu's irregularity

### ISSUE THREAD

**Issue by cristiansc** [adventistmedia/adventisthub-support#56]
When autofill is activated on some drop down menus, it doesn't work properly.

e.g. when adding new user via the add team member from within a team's member list, a drop down autofill list comes up which can only be removed by click in the text field box, and hitting escape. Clicking outside the autofill dropdown or anywhere else doesn't remove it - which is cumbersome if you don't know the click/escape routine.

**Comment by cristiansc** [comment]
hi guys - this is still happening and making it quite difficult at times to add data

e.g. tried to create new user 'Jacob U' for team SQLD Team - a drop down appeared with 3-4 other possible existing users (none of which were Jacob) - could not click/hide the drop down menu so I could keep typing - had to press enter/select one of the names, then delete all the data and start typing again

**Comment by lasedgman** [comment]
Auto fill will be fixed with _Dash_

**Comment by brettdonald** [comment]
Fixed. 

The problem was that if the user tabs away from the email address field before the autocomplete has finished its work, the autocomplete would still display even though the user has moved on. The autocomplete process takes roughly one second to complete following each keystroke. AdHub waits 500ms after each keypress before triggering the autocomplete search, and then the search itself takes around 500ms. If the user types the email address, pauses until the autocomplete drop-down appears, then presses Tab, the drop-down is cleared as expected. However, if user does _not_ pause, the drop-down then appears over the next field and is difficult to clear.

We have altered the plugin code to set a state flag when the user presses the tab key, which prevents the drop-down from being displayed.
